# Generated by Django 3.2.6 on 2021-08-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0003_auto_20210813_1404'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Currrent_coord',
            new_name='Current_coord',
        ),
    ]
